export const SITE_TYPE_REFS_PARAMS: Record<string, string> = {
  site_id: 'Site ID',
  english_name: 'English name',
  french_name: 'French name',
  khmer_name: 'Khmer name',
  alternative_name: 'Alternative name',
  alternative_khmer_name: 'Alternative Khmer name',
  description: 'Description',
  ik_id: 'IK ID',
  mh_id: 'MH ID',
  verified: 'Verified',
  verification_date: 'Verification date',
  located_by: 'Located by',
  ceramics_details: 'Ceramics details',
  ceramics: 'Ceramics',
  build_material_comments: 'Build material comments',
  artefacts_comments: 'Artefacts comments',
  looted: 'Looted',
  cultivated: 'Cultivated',
  cleared: 'Cleared',
  threatened: 'Threatened',
  databasing_comments: 'Databasing comments',
  creation_date: 'Creation date',
  modification_date: 'Modification date',
  user_creation: 'Created by',
  user_modification: 'Modified by',
  feature_type_id: 'Feature type',
  study_area: 'Study area',
};
